os: linux
language: php
php:
  - '7.2'

stages:
 - build
 - name: deploy
   if: tag =~ ^v

jobs:
  include:
   - stage: build
     name: "pack archive"
     before_script: composer install
     script:
       - zip -r wp-vereinsflieger.zip languages src vendor wp-vereinsflieger.php readme.txt
       - zip -r wp-vereinsflieger-assets.zip wp-assets
     workspaces:
       create:
         name: plugin-build
         paths:
          - wp-vereinsflieger.zip
          - wp-vereinsflieger-assets.zip

   - stage: deploy
     name: "deploy to github"
     workspaces:
       use:
        - plugin-build
     script: skip
     deploy:
       provider: releases
       token:
         secure: V/uGTDJnGUd+EmMMJwMB1wxMRAy7qJQDSqVtqcU+Qpob8V/3qqVICaSWqHI9nBedSbCgs+Itx+ctnQxXUYzLWQ01db+6Nkj9YmlihOwSDHisfY1xUbe5A2x2/mhY15O6JfO6zOKrV0jh6V1Cl/JeKsuUhUdYf3SPgJR7xIegqlxcY2YsShgAuF9GqI8HqLuloJGj0U+Tdhje9FLVEnRlgw1XJccb7ue8Sofjg/FO5WAahTwGTS1NPQlXqTqJJjdpx+MbXMOxE5R7oZhH60cmZj1/yDV0ZMJnrXV8l3L502C0n8cdZjUdbrOqdTTqQ6rilKLeZYc10BXgG142vxiRvZ1vi0ytPCn3bO946OLrOwtyEh3ZRjIcAxW47EN5cqOnKBZr6ulhmyZ4jUT8GBZ+MpL1GBUwX9osP07ehWlBg190sYwWOLUBS0w5loaMM9E284+PjPWwfn3yixxdVAmjFOw9xZ3eHEkqsreBdCmk88lft+GLm6xRyXeC6iViF7wZYntgGqTvfy1uhLWbORP51/dYHNKoIT047n8piihOrI0IECxstZVFxlKA3vw39HtfFAhT4rVaudehpkjn++4M6m2ttqqL71Oo6CSdnvH5TVpBj75k71II1o4FMup0psL7LOb8Z2O2vxWDGQIYjqnindHZHFFUYTmv9xNA5llOJY0=
       file: wp-vereinsflieger.zip
       on:
         tags: true
       skip_cleanup: true
     
   - stage: deploy
     name: "deploy to wordpress"
     workspaces:
       use:
        - plugin-build
     before_script:
       - sudo apt update
       - sudo apt install -y subversion
     script:
       - unzip -d build wp-vereinsflieger.zip
       - unzip -d assets wp-vereinsflieger-assets.zip
       - STABLE_TAG=$(awk '/^Stable tag:/ { print $3 }' build/readme.txt)
       - if [ "v${STABLE_TAG}" != $TRAVIS_TAG ]; then echo "Tag version number does not match the version number in readme.txt."; exit 1; fi;
       - svn checkout --non-interactive --trust-server-cert https://plugins.svn.wordpress.org/wp-vereinsflieger wp-svn
       - if [ -d "./wp-svn/tags/${STABLE_TAG}" ]; then echo "Version already exists in SVN repository."; exit 1; fi;
       - rm -fr ./wp-svn/assets/*
       - cp -r ./assets/wp-assets/* ./wp-svn/assets/
       - svn propset svn:mime-type image/png ./wp-svn/assets/*.png
       - svn propset svn:mime-type image/jpeg ./wp-svn/assets/*.jpg
       - svn propset svn:mime-type image/svg+xml ./wp-svn/assets/*.svg
       - rm -fr ./wp-svn/trunk/*
       - cp -r ./build/* ./wp-svn/trunk/
       - mkdir "./wp-svn/tags/${STABLE_TAG}"
       - cp -r ./wp-svn/trunk/* "./wp-svn/tags/${STABLE_TAG}/"
       - svn add --force ./wp-svn/*
       - svn commit --username "$SVN_USER" --password "$SVN_PASSWORD" --non-interactive --trust-server-cert -m "auto deployment from github repository" ./wp-svn
